function lua = femm_baseplate_spreading(cfg)
% femm_baseplate_spreading - generate FEMM Lua script for baseplate spreading 2D planar model
%
% 2D planar rectangular baseplate with heat sources on top and convection on bottom.
% Geometry: rectangle from (0,0) to (a, tb).
%   Top surface (y=tb): subdivided at source boundaries, heat flux BCs on source
%                        segments, insulated on gaps between sources.
%   Bottom surface (y=0): convection BC.
%   Left (x=0) and right (x=a) edges: insulated (symmetry).
%
% Input:
%   cfg - config struct with fields:
%     cfg.heatsink.width         - plate total width a [m]
%     cfg.heatsink.baseThickness - plate thickness tb [m]
%     cfg.heatsink.kPlate        - thermal conductivity [W/(m*K)]
%     cfg.convection.h           - convection coefficient [W/(m^2*K)]
%     cfg.convection.tFluid      - fluid temperature [K]
%     cfg.sources.power          - array of source powers [W]
%     cfg.sources.x              - array of source center x positions [m]
%     cfg.sources.width          - array of source widths [m]
%
% Output:
%   lua - string containing the complete FEMM Lua script

    L = {};  % cell array of lines

    % ---------------------------------------------------------------
    % Geometry parameters
    % ---------------------------------------------------------------
    a   = cfg.heatsink.width;
    tb  = cfg.heatsink.baseThickness;
    k   = cfg.heatsink.kPlate;
    h   = cfg.convection.h;
    Tf  = cfg.convection.tFluid;

    nSrc = length(cfg.sources.power);
    srcP = cfg.sources.power;
    srcX = cfg.sources.x;
    srcW = cfg.sources.width;

    % Compute x-boundaries for each source segment [x_left, x_right]
    srcLeft  = srcX - srcW/2;
    srcRight = srcX + srcW/2;

    % Compute heat flux for each source (q = P / (W_src * depth))
    % Depth is 1 m for 2D planar analysis (per unit depth)
    srcQ = srcP ./ srcW;  % [W/m^2] per unit depth

    % ---------------------------------------------------------------
    % Header and problem definition
    % ---------------------------------------------------------------
    L{end+1} = '-- Auto-generated by femm_baseplate_spreading.m';
    L{end+1} = '-- 2D planar: baseplate spreading with multiple heat sources';
    L{end+1} = '';
    L{end+1} = 't1 = clock()';
    L{end+1} = 'newdocument(2)';
    L{end+1} = '';
    L{end+1} = '-- Problem definition: meters, planar';
    L{end+1} = 'hi_probdef("meters","planar",1e-8,20,30)';
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Materials
    % ---------------------------------------------------------------
    L{end+1} = '-- Materials';
    L{end+1} = sprintf('hi_addmaterial("plate", %.6g, %.6g, 0)', k, k);
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Boundary conditions
    % ---------------------------------------------------------------
    L{end+1} = '-- Boundary conditions';
    % Convection on bottom face
    L{end+1} = sprintf('hi_addboundprop("conv_bottom", 2, 0, 0, %.6g, %.6g)', Tf, h);
    % Insulated on left, right, and top gaps
    L{end+1} = 'hi_addboundprop("insulated", 1, 0, 0)';
    % Heat flux for each source
    for i = 1:nSrc
        L{end+1} = sprintf('hi_addboundprop("source_%d", 1, 0, %.6g)', i, srcQ(i));
    end
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Geometry parameters as Lua variables
    % ---------------------------------------------------------------
    L{end+1} = '-- Geometry parameters';
    L{end+1} = sprintf('a  = %.10g', a);
    L{end+1} = sprintf('tb = %.10g', tb);
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Build sorted list of x-breakpoints on top surface
    % ---------------------------------------------------------------
    % Collect all unique x values: 0, source left/right edges, a
    xBreaks = unique([0, srcLeft, srcRight, a]);

    % ---------------------------------------------------------------
    % Nodes
    % ---------------------------------------------------------------
    L{end+1} = '-- Nodes';

    % Bottom corners
    L{end+1} = 'hi_addnode(0,  0)';
    L{end+1} = 'hi_addnode(a,  0)';

    % Top surface nodes at all x-breakpoints
    for i = 1:length(xBreaks)
        L{end+1} = sprintf('hi_addnode(%.10g, tb)', xBreaks(i));
    end
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Segments
    % ---------------------------------------------------------------
    L{end+1} = '-- Segments';

    % Bottom edge
    L{end+1} = 'hi_addsegment(0, 0, a, 0)';

    % Left edge
    L{end+1} = 'hi_addsegment(0, 0, 0, tb)';

    % Right edge
    L{end+1} = 'hi_addsegment(a, 0, a, tb)';

    % Top surface: segment for each interval between breakpoints
    for i = 1:length(xBreaks)-1
        x1 = xBreaks(i);
        x2 = xBreaks(i+1);
        L{end+1} = sprintf('hi_addsegment(%.10g, tb, %.10g, tb)', x1, x2);
    end
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Block label (single material region)
    % ---------------------------------------------------------------
    L{end+1} = '-- Block labels';
    L{end+1} = sprintf('hi_addblocklabel(%.10g, %.10g)', a/2, tb/2);
    L{end+1} = '';
    L{end+1} = '-- Assign materials';
    L{end+1} = sprintf('hi_selectlabel(%.10g, %.10g)', a/2, tb/2);
    L{end+1} = 'hi_setblockprop("plate", 0, 0.05, 0)';
    L{end+1} = 'hi_clearselected()';
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Apply boundary conditions
    % ---------------------------------------------------------------
    L{end+1} = '-- Apply boundary conditions';

    % Bottom: convection
    L{end+1} = sprintf('hi_selectsegment(%.10g, 0)', a/2);
    L{end+1} = 'hi_setsegmentprop("conv_bottom", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    L{end+1} = '';

    % Left edge: insulated
    L{end+1} = sprintf('hi_selectsegment(0, %.10g)', tb/2);
    L{end+1} = 'hi_setsegmentprop("insulated", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';

    % Right edge: insulated
    L{end+1} = sprintf('hi_selectsegment(a, %.10g)', tb/2);
    L{end+1} = 'hi_setsegmentprop("insulated", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    L{end+1} = '';

    % Top surface segments: assign source BC or insulated
    for i = 1:length(xBreaks)-1
        x1 = xBreaks(i);
        x2 = xBreaks(i+1);
        xMid = (x1 + x2) / 2;

        % Determine if this segment falls inside any source
        bcName = 'insulated';
        for j = 1:nSrc
            if xMid >= srcLeft(j) && xMid <= srcRight(j)
                bcName = sprintf('source_%d', j);
                break;
            end
        end

        L{end+1} = sprintf('hi_selectsegment(%.10g, tb)', xMid);
        L{end+1} = sprintf('hi_setsegmentprop("%s", 0, 1, 0, 0, "<None>")', bcName);
        L{end+1} = 'hi_clearselected()';
    end
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Solve
    % ---------------------------------------------------------------
    L{end+1} = '-- Solve';
    L{end+1} = 'hi_zoomnatural()';
    L{end+1} = 'hi_saveas("baseplate_spreading.feh")';
    L{end+1} = 'hi_analyze()';
    L{end+1} = 'hi_loadsolution()';
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Extract results to CSV
    % ---------------------------------------------------------------
    L{end+1} = '-- Extract results to CSV';
    L{end+1} = 'outfile = openfile("baseplate_spreading_results.csv", "w")';
    L{end+1} = 'write(outfile, "point,x,y,temperature_K\n")';

    % Temperature at each source center (top surface)
    for i = 1:nSrc
        L{end+1} = sprintf('v = ho_getpointvalues(%.10g, tb)', srcX(i));
        L{end+1} = sprintf('write(outfile, string.format("source_%d_top,%.10g,%.10g,%%s\\n", tostring(v[1])))', ...
            i, srcX(i), tb);
    end

    % Temperature at bottom center
    L{end+1} = sprintf('v = ho_getpointvalues(%.10g, 0)', a/2);
    L{end+1} = sprintf('write(outfile, string.format("bottom_center,%.10g,0,%%s\\n", tostring(v[1])))', a/2);

    L{end+1} = 'closefile(outfile)';
    L{end+1} = '';

    L{end+1} = 't2 = clock()';
    L{end+1} = 'print(t2-t1)';

    % ---------------------------------------------------------------
    % Join all lines
    % ---------------------------------------------------------------
    lua = strjoin(L, '\n');
end
