function lua = femm_semi_on_pcb(cfg)
% femm_semi_on_pcb - generate FEMM Lua script for semi-on-PCB axisymmetric model
%
% Input:
%   cfg - config struct with fields:
%     cfg.areaContact      - contact area [m^2] -> source radius rc = sqrt(A/pi)
%     cfg.areaDissBottom   - bottom dissipation area [m^2] -> outer radius b = sqrt(A/pi)
%     cfg.pcbLayerStack    - Nx2 [thickness(m), conductivity(W/mK)]
%     cfg.sinkLayerStack   - Mx2 [thickness(m), conductivity(W/mK)]
%     cfg.pLossJunction    - power loss [W]
%     cfg.hFluidBottom     - bottom convection coeff [W/m^2K]
%     cfg.tempFluidBottom  - bottom fluid temperature [K]
%     cfg.includeTop       - bool: apply convection BC on top outer ring
%     cfg.hFluidTop        - top convection coeff [W/m^2K] (used if includeTop)
%     cfg.tempFluidTop     - top fluid temperature [K] (used if includeTop)
%
% Output:
%   lua - string containing the complete FEMM Lua script

    L = {};  % cell array of lines

    % ---------------------------------------------------------------
    % Header and problem definition
    % ---------------------------------------------------------------
    L{end+1} = '-- Auto-generated by femm_semi_on_pcb.m';
    L{end+1} = '-- Axisymmetric heat flow: semiconductor on PCB';
    L{end+1} = '';
    L{end+1} = 't1 = clock()';
    L{end+1} = 'newdocument(2)';
    L{end+1} = '';
    L{end+1} = '-- Problem definition: meters, axisymmetric';
    L{end+1} = 'hi_probdef("meters","axi",1e-8,20,30)';
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Compute geometry parameters
    % ---------------------------------------------------------------
    rc = sqrt(cfg.areaContact / pi);
    b  = sqrt(cfg.areaDissBottom / pi);
    P  = cfg.pLossJunction(1);
    q  = -P / cfg.areaContact;  % heat flux [W/m^2], negative = into domain

    % ---------------------------------------------------------------
    % Collect unique materials from pcbLayerStack and sinkLayerStack
    % ---------------------------------------------------------------
    L{end+1} = '-- Materials';
    allLayers = [cfg.pcbLayerStack; cfg.sinkLayerStack];
    matNames = {};
    matK     = [];
    for i = 1:size(allLayers, 1)
        k = allLayers(i, 2);
        % Check if this conductivity already has a name
        found = false;
        for j = 1:length(matK)
            if abs(matK(j) - k) < 1e-9
                found = true;
                break;
            end
        end
        if ~found
            matNames{end+1} = sprintf('mat_k%.4g', k);
            matK(end+1) = k;
        end
    end
    for i = 1:length(matNames)
        L{end+1} = sprintf('hi_addmaterial("%s", %.6g, %.6g, 0)', ...
            matNames{i}, matK(i), matK(i));
    end
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Boundary conditions
    % ---------------------------------------------------------------
    L{end+1} = '-- Boundary conditions';
    % Heat flux on source (chip contact) - type 1 = heat flux
    L{end+1} = sprintf('hi_addboundprop("heatflux_source", 1, 0, %.6g)', q);
    % Convection on bottom - type 2 = convection
    L{end+1} = sprintf('hi_addboundprop("conv_bottom", 2, 0, 0, %.6g, %.6g)', ...
        cfg.tempFluidBottom, cfg.hFluidBottom);
    % Top BC: convection or insulated (h=0)
    if isfield(cfg, 'includeTop') && cfg.includeTop
        L{end+1} = sprintf('hi_addboundprop("conv_top", 2, 0, 0, %.6g, %.6g)', ...
            cfg.tempFluidTop, cfg.hFluidTop);
    else
        L{end+1} = 'hi_addboundprop("insulated_top", 2, 0, 0, 293.15, 0)';
    end
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Geometry parameters as Lua variables
    % ---------------------------------------------------------------
    L{end+1} = '-- Geometry parameters';
    L{end+1} = sprintf('rc = %.10g', rc);
    L{end+1} = sprintf('b  = %.10g', b);
    L{end+1} = 'l  = rc * 0.01   -- small offset for block labels';
    L{end+1} = '';

    % Build y-coordinate list: y0=0 at top, layers stack downward
    % PCB layers first, then sink layers
    nPcb  = size(cfg.pcbLayerStack, 1);
    nSink = size(cfg.sinkLayerStack, 1);
    nLayers = nPcb + nSink;

    % Emit y-level variables
    L{end+1} = 'y0 = 0';
    yLevels = zeros(1, nLayers + 1);  % y0 .. y_nLayers
    yLevels(1) = 0;
    for i = 1:nLayers
        if i <= nPcb
            th = cfg.pcbLayerStack(i, 1);
        else
            th = cfg.sinkLayerStack(i - nPcb, 1);
        end
        yLevels(i+1) = yLevels(i) - th;
        L{end+1} = sprintf('y%d = %.10g', i, yLevels(i+1));
    end
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Nodes
    % ---------------------------------------------------------------
    L{end+1} = '-- Nodes';

    % Top surface (y0=0): r=0, rc, b
    L{end+1} = 'hi_addnode(0, y0)';
    L{end+1} = 'hi_addnode(rc, y0)';
    L{end+1} = 'hi_addnode(b, y0)';

    % Intermediate layer interfaces
    % The geometry has two columns: inner (r=0..rc) and outer (r=rc..b).
    % At y0 and y_nLayers the full width r=0..b is present.
    % At intermediate levels: inner column only exists from y1 to y_{nPcb}
    % (where the via/contact area spans), and outer column spans full width.
    % For simplicity we use a two-column model at every layer interface.
    for i = 1:nLayers
        yvar = sprintf('y%d', i);
        if i == nLayers
            % Bottom: full width
            L{end+1} = sprintf('hi_addnode(0, %s)', yvar);
            L{end+1} = sprintf('hi_addnode(b, %s)', yvar);
        else
            % Mid-level: rc and b columns only (inner column runs straight)
            L{end+1} = sprintf('hi_addnode(rc, %s)', yvar);
            L{end+1} = sprintf('hi_addnode(b,  %s)', yvar);
        end
    end
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Segments (edges)
    % ---------------------------------------------------------------
    L{end+1} = '-- Segments';

    % Top surface
    L{end+1} = 'hi_addsegment(0,  y0, rc, y0)';   % source segment
    L{end+1} = 'hi_addsegment(rc, y0, b,  y0)';   % outer top

    % Vertical and horizontal segments for each layer
    % Inner vertical: r=0 from y0 to y_nPcb (only spans PCB layers, then uses rc col)
    % Outer vertical: r=b from y0 to y_nLayers
    % We emit per-layer verticals and horizontal interfaces

    % First: top outer verticals for first layer
    L{end+1} = sprintf('hi_addsegment(b, y0, b, y1)');

    % For first PCB layer: inner edge at r=0 from y0 to y1
    L{end+1} = 'hi_addsegment(0, y0, 0, y1)';
    % horizontal at y1
    L{end+1} = 'hi_addsegment(0, y1, rc, y1)';
    L{end+1} = 'hi_addsegment(rc, y1, b, y1)';

    % Inner vertical continues at r=0 down through all PCB layers
    for i = 2:nPcb
        prev = sprintf('y%d', i-1);
        curr = sprintf('y%d', i);
        L{end+1} = sprintf('hi_addsegment(0,  %s, 0,  %s)', prev, curr);
        L{end+1} = sprintf('hi_addsegment(rc, %s, rc, %s)', prev, curr);
        L{end+1} = sprintf('hi_addsegment(b,  %s, b,  %s)', prev, curr);
        L{end+1} = sprintf('hi_addsegment(0,  %s, rc, %s)', curr, curr);
        L{end+1} = sprintf('hi_addsegment(rc, %s, b,  %s)', curr, curr);
    end

    % Sink layers: only rc and b columns (inner goes to 0 at bottom)
    for i = (nPcb+1):nLayers
        prev = sprintf('y%d', i-1);
        curr = sprintf('y%d', i);
        if i == nLayers
            % bottom level: r=0 column resumes, vertical segments down
            L{end+1} = sprintf('hi_addsegment(0,  %s, 0,  %s)', prev, curr);
            L{end+1} = sprintf('hi_addsegment(b,  %s, b,  %s)', prev, curr);
            L{end+1} = sprintf('hi_addsegment(0,  %s, b,  %s)', curr, curr);
        else
            L{end+1} = sprintf('hi_addsegment(rc, %s, rc, %s)', prev, curr);
            L{end+1} = sprintf('hi_addsegment(b,  %s, b,  %s)', prev, curr);
            L{end+1} = sprintf('hi_addsegment(rc, %s, b,  %s)', curr, curr);
        end
    end

    % Bottom edge
    L{end+1} = sprintf('hi_addsegment(0, y%d, b, y%d)', nLayers, nLayers);
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Block labels and material assignment
    % ---------------------------------------------------------------
    L{end+1} = '-- Block labels';

    % For each layer, place a label at (rc+l, y_prev - th/2) in outer column
    % and for PCB layers, also in inner column at (l, y_prev - th/2)
    for i = 1:nLayers
        yTop = yLevels(i);
        yBot = yLevels(i+1);
        yMid = (yTop + yBot) / 2;

        if i <= nPcb
            k = cfg.pcbLayerStack(i, 2);
        else
            k = cfg.sinkLayerStack(i - nPcb, 2);
        end
        matName = '';
        for j = 1:length(matK)
            if abs(matK(j) - k) < 1e-9
                matName = matNames{j};
                break;
            end
        end

        % Outer column label
        L{end+1} = sprintf('hi_addblocklabel(rc+l, %.10g)', yMid);
        % Inner column label for PCB layers
        if i <= nPcb
            L{end+1} = sprintf('hi_addblocklabel(l, %.10g)', yMid);
        end
    end
    L{end+1} = '';

    % Assign materials
    L{end+1} = '-- Assign materials';
    for i = 1:nLayers
        yTop = yLevels(i);
        yBot = yLevels(i+1);
        yMid = (yTop + yBot) / 2;

        if i <= nPcb
            k = cfg.pcbLayerStack(i, 2);
        else
            k = cfg.sinkLayerStack(i - nPcb, 2);
        end
        matName = '';
        for j = 1:length(matK)
            if abs(matK(j) - k) < 1e-9
                matName = matNames{j};
                break;
            end
        end

        % Outer column
        L{end+1} = sprintf('hi_selectlabel(rc+l, %.10g)', yMid);
        if i <= nPcb
            L{end+1} = sprintf('hi_selectlabel(l, %.10g)', yMid);
        end
        L{end+1} = sprintf('hi_setblockprop("%s", 0, 0.05, 0)', matName);
        L{end+1} = 'hi_clearselected()';
    end
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Apply boundary conditions to segments
    % ---------------------------------------------------------------
    L{end+1} = '-- Apply boundary conditions';

    % Source: top surface inner segment at midpoint (l, y0)
    L{end+1} = 'hi_selectsegment(l, y0)';
    L{end+1} = 'hi_setsegmentprop("heatflux_source", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    L{end+1} = '';

    % Bottom convection: bottom edge midpoint
    L{end+1} = sprintf('hi_selectsegment(b*0.5, y%d)', nLayers);
    L{end+1} = 'hi_setsegmentprop("conv_bottom", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    L{end+1} = '';

    % Top outer ring BC
    if isfield(cfg, 'includeTop') && cfg.includeTop
        L{end+1} = 'hi_selectsegment(rc+l, y0)';
        L{end+1} = 'hi_setsegmentprop("conv_top", 0, 1, 0, 0, "<None>")';
    else
        L{end+1} = 'hi_selectsegment(rc+l, y0)';
        L{end+1} = 'hi_setsegmentprop("insulated_top", 0, 1, 0, 0, "<None>")';
    end
    L{end+1} = 'hi_clearselected()';
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Solve
    % ---------------------------------------------------------------
    L{end+1} = '-- Solve';
    L{end+1} = 'hi_zoomnatural()';
    L{end+1} = 'hi_saveas("semi_on_pcb.feh")';
    L{end+1} = 'hi_analyze()';
    L{end+1} = 'hi_loadsolution()';
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Extract results to CSV
    % ---------------------------------------------------------------
    L{end+1} = '-- Extract results to CSV';
    L{end+1} = 'outfile = openfile("semi_on_pcb_results.csv", "w")';
    L{end+1} = 'write(outfile, "point,r,y,temperature_K\n")';

    % Junction point: (0, 0)
    L{end+1} = 'v = ho_getpointvalues(0, y0)';
    L{end+1} = 'write(outfile, string.format("junction,0,0,%.6f\n", v[1]))';

    % PCB bottom interface: (0, y_nPcb)
    L{end+1} = sprintf('v = ho_getpointvalues(0, y%d)', nPcb);
    L{end+1} = sprintf('write(outfile, string.format("pcb_bottom,0,%.10g,%%s\\n", tostring(v[1])))', yLevels(nPcb+1));

    % Model bottom: (b/2, y_nLayers)
    L{end+1} = sprintf('v = ho_getpointvalues(b*0.5, y%d)', nLayers);
    L{end+1} = sprintf('write(outfile, string.format("model_bottom,%.10g,%.10g,%%s\\n", b*0.5, tostring(v[1])))', b/2, yLevels(nLayers+1));

    L{end+1} = 'closefile(outfile)';
    L{end+1} = '';

    L{end+1} = 't2 = clock()';
    L{end+1} = 'print(t2-t1)';

    % ---------------------------------------------------------------
    % Join all lines
    % ---------------------------------------------------------------
    lua = strjoin(L, '\n');
end
