function lua = femm_extruded_fin(cfg)
% femm_extruded_fin - generate FEMM Lua script for extruded-fin 2D planar model
%
% 2D planar cross-section of half a fin channel (symmetry).
% Coordinate conventions:
%   x=0          : symmetry axis (fin center)
%   x=tf/2       : fin edge / channel wall
%   x=tf/2+wch/2 : channel center (symmetry, right boundary)
%   y=0          : base bottom (heat flux from component)
%   y=tb         : base top / channel+fin start
%   y=tb+Hf      : fin top
%
% Input:
%   cfg - config struct with fields:
%     cfg.heatsink.thickWall     - fin thickness tf [m]
%     cfg.heatsink.widthChannel  - channel width wch [m]
%     cfg.heatsink.thickHeatsink - base thickness tb [m]
%     cfg.heatsink.heightTotal   - total height (tb + Hf) [m]
%     cfg.heatsink.kSink         - thermal conductivity [W/(m*K)]
%     cfg.fluid.tInlet           - fluid inlet temperature [K]
%     cfg.heating.pLoss          - power loss [W]
%     cfg.heating.widthContact   - contact width [m]
%     cfg.heating.lengthContact  - contact length [m]
%     cfg.h_channel              - (optional) convection coeff [W/(m^2*K)], default 500
%
% Output:
%   lua - string containing the complete FEMM Lua script

    L = {};  % cell array of lines

    % ---------------------------------------------------------------
    % Geometry parameters
    % ---------------------------------------------------------------
    tf  = cfg.heatsink.thickWall;
    wch = cfg.heatsink.widthChannel;
    tb  = cfg.heatsink.thickHeatsink;
    H   = cfg.heatsink.heightTotal;
    Hf  = H - tb;
    k   = cfg.heatsink.kSink;

    % Half widths (symmetry model)
    xFin    = tf / 2;                % fin half-width (x at fin/channel boundary)
    xRight  = tf / 2 + wch / 2;     % right symmetry boundary (channel half-width)

    % Heat flux on base bottom
    q = cfg.heating.pLoss / (cfg.heating.widthContact * cfg.heating.lengthContact);

    % Convection coefficient (default 500 W/m^2K if not provided)
    if isfield(cfg, 'h_channel')
        h_conv = cfg.h_channel;
    else
        h_conv = 500;
    end
    t_fluid = cfg.fluid.tInlet;

    % ---------------------------------------------------------------
    % Header and problem definition
    % ---------------------------------------------------------------
    L{end+1} = '-- Auto-generated by femm_extruded_fin.m';
    L{end+1} = '-- 2D planar: extruded fin cross-section (half channel, symmetry)';
    L{end+1} = '';
    L{end+1} = 't1 = clock()';
    L{end+1} = 'newdocument(2)';
    L{end+1} = '';
    L{end+1} = '-- Problem definition: meters, planar';
    L{end+1} = 'hi_probdef("meters","planar",1e-8,20,30)';
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Materials
    % ---------------------------------------------------------------
    L{end+1} = '-- Materials';
    L{end+1} = sprintf('hi_addmaterial("heatsink", %.6g, %.6g, 0)', k, k);
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Boundary conditions
    % ---------------------------------------------------------------
    L{end+1} = '-- Boundary conditions';
    % Heat flux on base bottom
    L{end+1} = sprintf('hi_addboundprop("heatflux_base", 1, 0, %.6g)', q);
    % Convection on channel walls (fin right face, channel bottom, fin top)
    L{end+1} = sprintf('hi_addboundprop("convection", 2, 0, 0, %.6g, %.6g)', ...
        t_fluid, h_conv);
    % Symmetry (insulated) on left and right edges
    L{end+1} = 'hi_addboundprop("symmetry", 1, 0, 0)';
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Geometry parameters as Lua variables
    % ---------------------------------------------------------------
    L{end+1} = '-- Geometry parameters';
    L{end+1} = sprintf('xFin   = %.10g', xFin);
    L{end+1} = sprintf('xRight = %.10g', xRight);
    L{end+1} = sprintf('tb     = %.10g', tb);
    L{end+1} = sprintf('H      = %.10g', H);
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Nodes
    % ---------------------------------------------------------------
    % Base plate corners: (0,0), (xRight,0), (xRight,tb), (0,tb)
    % Fin corners: (0,tb), (xFin,tb), (xFin,H), (0,H)
    % Channel boundary nodes: (xFin,tb), (xRight,tb), (xRight,H)
    L{end+1} = '-- Nodes';
    L{end+1} = 'hi_addnode(0,      0)';
    L{end+1} = 'hi_addnode(xRight, 0)';
    L{end+1} = 'hi_addnode(0,      tb)';
    L{end+1} = 'hi_addnode(xFin,   tb)';
    L{end+1} = 'hi_addnode(xRight, tb)';
    L{end+1} = 'hi_addnode(0,      H)';
    L{end+1} = 'hi_addnode(xFin,   H)';
    L{end+1} = 'hi_addnode(xRight, H)';
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Segments
    % ---------------------------------------------------------------
    L{end+1} = '-- Segments';

    % Base plate boundary
    L{end+1} = 'hi_addsegment(0,      0,      xRight, 0)';      % base bottom (heat flux)
    L{end+1} = 'hi_addsegment(xRight, 0,      xRight, tb)';     % base right (symmetry)
    L{end+1} = 'hi_addsegment(0,      0,      0,      tb)';     % base left (symmetry)
    % Base top: split at xFin (under fin) and xFin->xRight (channel bottom)
    L{end+1} = 'hi_addsegment(0,      tb,     xFin,   tb)';     % base top under fin
    L{end+1} = 'hi_addsegment(xFin,   tb,     xRight, tb)';     % channel bottom (convection)

    % Fin boundary
    L{end+1} = 'hi_addsegment(0,      tb,     0,      H)';      % fin left (symmetry)
    L{end+1} = 'hi_addsegment(xFin,   tb,     xFin,   H)';      % fin right / channel wall (convection)
    L{end+1} = 'hi_addsegment(0,      H,      xFin,   H)';      % fin top (convection)

    % Channel right edge (symmetry)
    L{end+1} = 'hi_addsegment(xRight, tb,     xRight, H)';      % channel right (symmetry)
    % Channel top
    L{end+1} = 'hi_addsegment(xFin,   H,      xRight, H)';      % channel top (symmetry/open)
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Block labels
    % ---------------------------------------------------------------
    L{end+1} = '-- Block labels';
    % Base plate: centroid at (xRight/2, tb/2)
    L{end+1} = sprintf('hi_addblocklabel(%.10g, %.10g)', xRight/2, tb/2);
    % Fin: centroid at (xFin/2, tb + Hf/2)
    L{end+1} = sprintf('hi_addblocklabel(%.10g, %.10g)', xFin/2, tb + Hf/2);
    L{end+1} = '';

    % Assign material to base plate
    L{end+1} = '-- Assign materials';
    L{end+1} = sprintf('hi_selectlabel(%.10g, %.10g)', xRight/2, tb/2);
    L{end+1} = 'hi_setblockprop("heatsink", 0, 0.05, 0)';
    L{end+1} = 'hi_clearselected()';
    % Assign material to fin
    L{end+1} = sprintf('hi_selectlabel(%.10g, %.10g)', xFin/2, tb + Hf/2);
    L{end+1} = 'hi_setblockprop("heatsink", 0, 0.05, 0)';
    L{end+1} = 'hi_clearselected()';
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Apply boundary conditions
    % ---------------------------------------------------------------
    L{end+1} = '-- Apply boundary conditions';

    % Heat flux on base bottom (midpoint of bottom edge)
    L{end+1} = sprintf('hi_selectsegment(%.10g, 0)', xRight/2);
    L{end+1} = 'hi_setsegmentprop("heatflux_base", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    L{end+1} = '';

    % Convection on channel walls:
    % 1) fin right side: midpoint (xFin, tb + Hf/2)
    L{end+1} = sprintf('hi_selectsegment(xFin, %.10g)', tb + Hf/2);
    L{end+1} = 'hi_setsegmentprop("convection", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    % 2) channel bottom: midpoint ((xFin+xRight)/2, tb)
    L{end+1} = sprintf('hi_selectsegment(%.10g, tb)', (xFin + xRight)/2);
    L{end+1} = 'hi_setsegmentprop("convection", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    % 3) fin top: midpoint (xFin/2, H)
    L{end+1} = sprintf('hi_selectsegment(%.10g, H)', xFin/2);
    L{end+1} = 'hi_setsegmentprop("convection", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    L{end+1} = '';

    % Symmetry (insulated) on left edges and right edge
    % Left of base: (0, tb/2)
    L{end+1} = sprintf('hi_selectsegment(0, %.10g)', tb/2);
    L{end+1} = 'hi_setsegmentprop("symmetry", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    % Left of fin: (0, tb + Hf/2)
    L{end+1} = sprintf('hi_selectsegment(0, %.10g)', tb + Hf/2);
    L{end+1} = 'hi_setsegmentprop("symmetry", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    % Right of base: (xRight, tb/2)
    L{end+1} = sprintf('hi_selectsegment(xRight, %.10g)', tb/2);
    L{end+1} = 'hi_setsegmentprop("symmetry", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    % Right of channel: (xRight, tb + Hf/2)
    L{end+1} = sprintf('hi_selectsegment(xRight, %.10g)', tb + Hf/2);
    L{end+1} = 'hi_setsegmentprop("symmetry", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    % Channel top: ((xFin+xRight)/2, H)
    L{end+1} = sprintf('hi_selectsegment(%.10g, H)', (xFin + xRight)/2);
    L{end+1} = 'hi_setsegmentprop("symmetry", 0, 1, 0, 0, "<None>")';
    L{end+1} = 'hi_clearselected()';
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Solve
    % ---------------------------------------------------------------
    L{end+1} = '-- Solve';
    L{end+1} = 'hi_zoomnatural()';
    L{end+1} = 'hi_saveas("extruded_fin.feh")';
    L{end+1} = 'hi_analyze()';
    L{end+1} = 'hi_loadsolution()';
    L{end+1} = '';

    % ---------------------------------------------------------------
    % Extract results to CSV
    % ---------------------------------------------------------------
    L{end+1} = '-- Extract results to CSV';
    L{end+1} = 'outfile = openfile("extruded_fin_results.csv", "w")';
    L{end+1} = 'write(outfile, "point,x,y,temperature_K\n")';

    % Base bottom center: (0, 0)
    L{end+1} = 'v = ho_getpointvalues(0, 0)';
    L{end+1} = 'write(outfile, string.format("base_bottom_center,0,0,%.6f\n", v[1]))';

    % Base top / fin base: (xFin/2, tb)
    L{end+1} = sprintf('v = ho_getpointvalues(%.10g, tb)', xFin/2);
    L{end+1} = sprintf('write(outfile, string.format("fin_base,%.10g,%.10g,%%s\\n", tostring(v[1])))', ...
        xFin/2, tb);

    % Fin tip center: (xFin/2, H)
    L{end+1} = sprintf('v = ho_getpointvalues(%.10g, H)', xFin/2);
    L{end+1} = sprintf('write(outfile, string.format("fin_tip,%.10g,%.10g,%%s\\n", tostring(v[1])))', ...
        xFin/2, H);

    L{end+1} = 'closefile(outfile)';
    L{end+1} = '';

    L{end+1} = 't2 = clock()';
    L{end+1} = 'print(t2-t1)';

    % ---------------------------------------------------------------
    % Join all lines
    % ---------------------------------------------------------------
    lua = strjoin(L, '\n');
end
